name: Wails build

on:
  push:
    tags:
      # Match any new tag
      - "*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: "spotlightify"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          - name: "spotlightify"
            platform: "windows/amd64"
            os: "windows-latest"
          - name: "spotlightify"
            platform: "darwin/universal"
            os: "macos-latest"

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install libx11-dev
        if: matrix.build.platform == 'linux/amd64'
        run: sudo apt-get update && sudo apt-get install -y libx11-dev

      - name: Build wails
        uses: petergmurphy/wails-build-action@main
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: "1.22.5"
          node-version: "20.11.1"
